[package]
name = "pocket_tts"
version = "0.1.0"
edition = "2024"

[dependencies]
mimi = { path = "../mimi-rs" }
sentencepiece = "0.13.1"

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hf-hub = "0.4"
kaudio = "0.2.1"

[features]
default = []
cuda = ["mimi/cuda"]
