[package]
name = "pocket-tts"
version = "0.1.0"
edition = "2024"

[dependencies]
mimi = { path = "../mimi-rs" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
safetensors = "0.4"
sentencepiece = "0.11"
rand = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
hf-hub = "0.4"
